// packages/svelte/src/AspicioEmbed.svelte
<!--
  Batteries-included embed: layer list + interactive preview in one
  component — a thin Svelte veneer over the framework-neutral
  <aspicio-embed> element from @aspicio/elements, styled like the Aspicio
  demo app (blueprint grid, dark panel) unless theme="none". Pass the DXF
  as `src` (text, File, Blob, ArrayBuffer) or `srcUrl`; everything else
  is optional.

    <AspicioEmbed srcUrl="/drawing.dxf" style="height: 480px" onloaded={...} />

  `bind:this` exposes `viewer()` — the full DrawingViewer for camera control;
  use AspicioPreview + AspicioLayerPanel directly when you need a custom layout.
-->
<script>
  import "@aspicio/elements";

  let {
    /** DXF data: text, File, Blob, or ArrayBuffer. The most recently set of src/srcUrl wins. */
    src = null,
    /** URL to fetch a DXF from. The most recently set of src/srcUrl wins. */
    srcUrl = null,
    /** Viewer options, applied at creation (changing them recreates the viewer). */
    options = undefined,
    /** Where the layer list sits: "left" | "right" | "none". */
    panel = "left",
    /** Visual theme. Defaults to the Aspicio demo look. */
    theme = "aspicio",
    /** Which palette the theme uses: "dark" | "light". Defaults to dark (SVELTE-10). */
    themeMode = "dark",
    /** Inline styles applied to the inner layer panel (CSSOM values, e.g. "300px"). */
    panelStyle = undefined,
    /** Show the built-in Download control (SVG / PNG export). */
    showDownload = true,
    /** Keyboard shortcuts on the focused viewer: F fit, +/- zoom, R reset, A show all. */
    shortcuts = false,
    /** ({ layers, stats }) after each successful load. */
    onloaded = undefined,
    /** (error) when a load fails. */
    onloaderror = undefined,
    /** (viewer | null) when the viewer is created or the element disconnects. */
    onviewerchange = undefined,
    /** (layer | null) for the layer under the cursor. */
    onhoverlayer = undefined,
    /** Extra attributes (class, style, …) forwarded to the element. */
    ...rest
  } = $props();

  // Assigned by bind:this (compiler-generated; linter can't see it).
  let el = null;

  /** The live DrawingViewer instance, or null before mount / after unmount. */
  export function viewer() {
    return el?.viewer ?? null;
  }

  // panelStyle is a property-only field on the element (rich object), and
  // Svelte lowercases template attribute names — assign it imperatively.
  $effect(() => {
    if (el) el.panelStyle = panelStyle;
  });
</script>

<aspicio-embed
  bind:this={el}
  {src}
  src-url={srcUrl}
  {options}
  {panel}
  {theme}
  theme-mode={themeMode}
  no-download={!showDownload || undefined}
  {shortcuts}
  onloaded={(e) => onloaded?.(e.detail)}
  onload-error={(e) => onloaderror?.(e.detail.error)}
  onviewer-change={(e) => onviewerchange?.(e.detail.viewer)}
  onhover-layer={(e) => onhoverlayer?.(e.detail.layer)}
  {...rest}
></aspicio-embed>

// packages/react/src/AspicioEmbed.tsx
import type { DrawingViewer, LayerInfo, ViewerStats } from "@aspicio/core";
import { AspicioEmbed as AspicioEmbedElement } from "@aspicio/elements";
import { createComponent } from "@lit/react";
import * as React from "react";
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import type { AspicioPreviewProps } from "./AspicioPreview.tsx";
import type { AspicioTheme, AspicioThemeMode } from "./theme.ts";

export interface AspicioEmbedProps extends AspicioPreviewProps {
  /** Where the layer list sits. Default: "left". */
  panel?: "left" | "right" | "none";
  /**
   * @deprecated Host CSS can't reach into the embed's shadow DOM, so a
   * class on the inner panel has no effect. Use `panelStyle`, the
   * `--aspicio-*` custom properties, or `::part(panel)` instead.
   */
  panelClassName?: string;
  /** Inline styles applied to the inner layer panel. */
  panelStyle?: CSSProperties;
  /** Visual theme. Defaults to the Aspicio demo look; "none" inherits the host. */
  theme?: AspicioTheme;
  /** Which palette the theme uses. Defaults to dark (REACT-9). */
  themeMode?: AspicioThemeMode;
}

const EmbedElement = createComponent({
  tagName: "aspicio-embed",
  elementClass: AspicioEmbedElement,
  react: React,
  events: {
    onLoadedEvent: "loaded",
    onLoadErrorEvent: "load-error",
    onViewerChangeEvent: "viewer-change",
    onHoverLayerEvent: "hover-layer",
  },
});

/** CSS properties that take unitless numbers (mirrors React's DOM handling). */
const UNITLESS = new Set([
  "opacity",
  "zIndex",
  "flex",
  "flexGrow",
  "flexShrink",
  "fontWeight",
  "lineHeight",
  "order",
  "zoom",
]);

/**
 * React allows numeric style values ("width: 220" → "220px"); the element
 * applies panelStyle via CSSOM, which doesn't convert — do it here.
 */
function toCssomStyle(style: CSSProperties): Partial<CSSStyleDeclaration> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(style)) {
    if (value == null) continue;
    out[key] = typeof value === "number" && !UNITLESS.has(key) ? `${value}px` : String(value);
  }
  return out as Partial<CSSStyleDeclaration>;
}

/**
 * Batteries-included embed: layer list + interactive preview in one
 * component — a thin React veneer over the framework-neutral
 * `<aspicio-embed>` element from @aspicio/elements, styled like the
 * Aspicio demo app (blueprint grid, dark panel) unless theme="none".
 * Pass the DXF as `src` (text, File, Blob, ArrayBuffer) or `srcUrl`;
 * everything else is optional.
 *
 *   <AspicioEmbed src={file} style={{ height: 480 }} />
 *
 * The forwarded ref (and onViewer) still expose the full DrawingViewer for
 * camera control; use AspicioPreview + AspicioLayerPanel directly when you need
 * a custom layout.
 */
export const AspicioEmbed = forwardRef<DrawingViewer | null, AspicioEmbedProps>(
  function AspicioEmbed(
    {
      panel = "left",
      panelClassName: _panelClassName,
      panelStyle,
      theme = "aspicio",
      themeMode = "dark",
      src,
      srcUrl,
      options,
      className,
      style,
      onLoaded,
      onError,
      onViewer,
      onHoverLayer,
      showDownload = true,
      shortcuts = false,
    },
    ref,
  ) {
    const [viewer, setViewer] = useState<DrawingViewer | null>(null);
    useImperativeHandle(ref, () => viewer as DrawingViewer, [viewer]);

    const callbacks = useRef({ onLoaded, onError, onViewer, onHoverLayer });
    callbacks.current = { onLoaded, onError, onViewer, onHoverLayer };

    // React detaches event listeners before the element disconnects, so the
    // element's final `viewer-change` (null) never reaches us — honor the
    // "null on unmount" contract from the veneer itself. Under StrictMode the
    // cleanup also runs mid-life (after the viewer already exists), so the
    // setup re-reads the element's live viewer to undo it.
    const elRef = useRef<AspicioEmbedElement | null>(null);
    const liveViewer = useRef<DrawingViewer | null>(null);
    const report = (next: DrawingViewer | null): void => {
      if (liveViewer.current === next) return;
      liveViewer.current = next;
      setViewer(next);
      callbacks.current.onViewer?.(next);
    };
    const reportRef = useRef(report);
    reportRef.current = report;
    useEffect(() => {
      reportRef.current(elRef.current?.viewer ?? null);
      return () => reportRef.current(null);
    }, []);

    const panelStyleCssom = useMemo(
      () => (panelStyle ? toCssomStyle(panelStyle) : undefined),
      [panelStyle],
    );

    return (
      <EmbedElement
        ref={elRef}
        className={className}
        style={style}
        src={src ?? null}
        srcUrl={srcUrl ?? null}
        options={options}
        panel={panel}
        theme={theme}
        theme-mode={themeMode}
        panelStyle={panelStyleCssom}
        noDownload={!showDownload}
        shortcuts={shortcuts}
        onLoadedEvent={(e: Event) => {
          callbacks.current.onLoaded?.(
            (e as CustomEvent<{ layers: LayerInfo[]; stats: ViewerStats }>).detail,
          );
        }}
        onLoadErrorEvent={(e: Event) => {
          callbacks.current.onError?.((e as CustomEvent<{ error: Error }>).detail.error);
        }}
        onViewerChangeEvent={(e: Event) => {
          report((e as CustomEvent<{ viewer: DrawingViewer | null }>).detail.viewer);
        }}
        onHoverLayerEvent={(e: Event) => {
          callbacks.current.onHoverLayer?.(
            (e as CustomEvent<{ layer: string | null }>).detail.layer,
          );
        }}
      />
    );
  },
);
